# Generated by CMake 2.8.12.2

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget hdf5 hdf5_cpp hdf5_hl hdf5_hl_cpp)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target hdf5
add_library(hdf5 SHARED IMPORTED)

set_target_properties(hdf5 PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "C:/Development/op3d_active/hdf5-1.8.13/msvc/src;C:/Development/op3d_active/hdf5-1.8.13/src"
)

# Create imported target hdf5_cpp
add_library(hdf5_cpp SHARED IMPORTED)

set_target_properties(hdf5_cpp PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "C:/Development/op3d_active/hdf5-1.8.13/msvc/c++/src;C:/Development/op3d_active/hdf5-1.8.13/c++/src"
)

# Create imported target hdf5_hl
add_library(hdf5_hl SHARED IMPORTED)

set_target_properties(hdf5_hl PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "C:/Development/op3d_active/hdf5-1.8.13/msvc/hl/src;C:/Development/op3d_active/hdf5-1.8.13/hl/src"
)

# Create imported target hdf5_hl_cpp
add_library(hdf5_hl_cpp SHARED IMPORTED)

set_target_properties(hdf5_hl_cpp PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "C:/Development/op3d_active/hdf5-1.8.13/msvc/hl/c++/src;C:/Development/op3d_active/hdf5-1.8.13/hl/c++/src"
)

# Import target "hdf5" for configuration "Debug"
set_property(TARGET hdf5 APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(hdf5 PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/Development/op3d_active/hdf5-1.8.13/msvc/vc141/x64/vs2017_Debug/hdf5_D.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "C:/Development/op3d_active/zlib-1.2.8/vc141/x64/vs2017_Release/zlib.lib"
  IMPORTED_LOCATION_DEBUG "C:/Development/op3d_active/hdf5-1.8.13/msvc/vc141/x64/vs2017_Debug/hdf5_D.dll"
  )

# Import target "hdf5_cpp" for configuration "Debug"
set_property(TARGET hdf5_cpp APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(hdf5_cpp PROPERTIES
  IMPORTED_IMPLIB_DEBUG "C:/Development/op3d_active/hdf5-1.8.13/msvc/vc141/x64/vs2017_Debug/hdf5_cpp_D.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "hdf5"
  IMPORTED_LOCATION_DEBUG "C:/Development/op3d_active/hdf5-1.8.13/msvc/vc141/x64/vs2017_Debug/hdf5_cpp_D.dll"
  )

# Import target "hdf5_hl" for configuration "Debug"
set_property(TARGET hdf5_hl APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(hdf5_hl PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/Development/op3d_active/hdf5-1.8.13/msvc/vc141/x64/vs2017_Debug/hdf5_hl_D.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "hdf5"
  IMPORTED_LOCATION_DEBUG "D:/Development/op3d_active/hdf5-1.8.13/msvc/vc141/x64/vs2017_Debug/hdf5_hl_D.dll"
  )

# Import target "hdf5_hl_cpp" for configuration "Debug"
set_property(TARGET hdf5_hl_cpp APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(hdf5_hl_cpp PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/Development/op3d_active/hdf5-1.8.13/msvc/vc141/x64/vs2017_Debug/hdf5_hl_cpp_D.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "hdf5_hl;hdf5"
  IMPORTED_LOCATION_DEBUG "D:/Development/op3d_active/hdf5-1.8.13/msvc/vc141/x64/vs2017_Debug/hdf5_hl_cpp_D.dll"
  )

# Import target "hdf5" for configuration "Release"
set_property(TARGET hdf5 APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(hdf5 PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/Development/op3d_active/hdf5-1.8.13/msvc/vc141/x64/vs2017_Release/hdf5.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "D:/Development/op3d_active/zlib-1.2.8/vc141/x64/vs2017_Release/zlib.lib"
  IMPORTED_LOCATION_RELEASE "D:/Development/op3d_active/hdf5-1.8.13/msvc/vc141/x64/vs2017_Release/hdf5.dll"
  )

# Import target "hdf5_cpp" for configuration "Release"
set_property(TARGET hdf5_cpp APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(hdf5_cpp PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/Development/op3d_active/hdf5-1.8.13/msvc/vc141/x64/vs2017_Release/hdf5_cpp.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "hdf5"
  IMPORTED_LOCATION_RELEASE "D:/Development/op3d_active/hdf5-1.8.13/msvc/vc141/x64/vs2017_Release/hdf5_cpp.dll"
  )

# Import target "hdf5_hl" for configuration "Release"
set_property(TARGET hdf5_hl APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(hdf5_hl PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/Development/op3d_active/hdf5-1.8.13/msvc/vc141/x64/vs2017_Release/hdf5_hl.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "hdf5"
  IMPORTED_LOCATION_RELEASE "D:/Development/op3d_active/hdf5-1.8.13/msvc/vc141/x64/vs2017_Release/hdf5_hl.dll"
  )

# Import target "hdf5_hl_cpp" for configuration "Release"
set_property(TARGET hdf5_hl_cpp APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(hdf5_hl_cpp PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/Development/op3d_active/hdf5-1.8.13/msvc/vc141/x64/vs2017_Release/hdf5_hl_cpp.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "hdf5_hl;hdf5"
  IMPORTED_LOCATION_RELEASE "D:/Development/op3d_active/hdf5-1.8.13/msvc/vc141/x64/vs2017_Release/hdf5_hl_cpp.dll"
  )

# Import target "hdf5" for configuration "MinSizeRel"
set_property(TARGET hdf5 APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(hdf5 PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "D:/Development/op3d_active/hdf5-1.8.13/msvc/vc141/x64/vs2017_Release/hdf5.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_MINSIZEREL "D:/Development/op3d_active/zlib-1.2.8/vc141/x64/vs2017_Release/zlib.lib"
  IMPORTED_LOCATION_MINSIZEREL "D:/Development/op3d_active/hdf5-1.8.13/msvc/bin/MinSizeRel/hdf5.dll"
  )

# Import target "hdf5_cpp" for configuration "MinSizeRel"
set_property(TARGET hdf5_cpp APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(hdf5_cpp PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "D:/Development/op3d_active/hdf5-1.8.13/msvc/bin/MinSizeRel/hdf5_cpp.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_MINSIZEREL "hdf5"
  IMPORTED_LOCATION_MINSIZEREL "D:/Development/op3d_active/hdf5-1.8.13/msvc/bin/MinSizeRel/hdf5_cpp.dll"
  )

# Import target "hdf5_hl" for configuration "MinSizeRel"
set_property(TARGET hdf5_hl APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(hdf5_hl PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "D:/Development/op3d_active/hdf5-1.8.13/msvc/bin/MinSizeRel/hdf5_hl.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_MINSIZEREL "hdf5"
  IMPORTED_LOCATION_MINSIZEREL "D:/Development/op3d_active/hdf5-1.8.13/msvc/bin/MinSizeRel/hdf5_hl.dll"
  )

# Import target "hdf5_hl_cpp" for configuration "MinSizeRel"
set_property(TARGET hdf5_hl_cpp APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(hdf5_hl_cpp PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "D:/Development/op3d_active/hdf5-1.8.13/msvc/bin/MinSizeRel/hdf5_hl_cpp.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_MINSIZEREL "hdf5_hl;hdf5"
  IMPORTED_LOCATION_MINSIZEREL "D:/Development/op3d_active/hdf5-1.8.13/msvc/bin/MinSizeRel/hdf5_hl_cpp.dll"
  )

# Import target "hdf5" for configuration "RelWithDebInfo"
set_property(TARGET hdf5 APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(hdf5 PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "D:/Development/op3d_active/hdf5-1.8.13/msvc/bin/RelWithDebInfo/hdf5.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELWITHDEBINFO "D:/Development/op3d_active/zlib-1.2.8/vc110/Win32/Release/zlib.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "D:/Development/op3d_active/hdf5-1.8.13/msvc/bin/RelWithDebInfo/hdf5.dll"
  )

# Import target "hdf5_cpp" for configuration "RelWithDebInfo"
set_property(TARGET hdf5_cpp APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(hdf5_cpp PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "D:/Development/op3d_active/hdf5-1.8.13/msvc/bin/RelWithDebInfo/hdf5_cpp.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELWITHDEBINFO "hdf5"
  IMPORTED_LOCATION_RELWITHDEBINFO "D:/Development/op3d_active/hdf5-1.8.13/msvc/bin/RelWithDebInfo/hdf5_cpp.dll"
  )

# Import target "hdf5_hl" for configuration "RelWithDebInfo"
set_property(TARGET hdf5_hl APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(hdf5_hl PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "D:/Development/op3d_active/hdf5-1.8.13/msvc/bin/RelWithDebInfo/hdf5_hl.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELWITHDEBINFO "hdf5"
  IMPORTED_LOCATION_RELWITHDEBINFO "D:/Development/op3d_active/hdf5-1.8.13/msvc/bin/RelWithDebInfo/hdf5_hl.dll"
  )

# Import target "hdf5_hl_cpp" for configuration "RelWithDebInfo"
set_property(TARGET hdf5_hl_cpp APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(hdf5_hl_cpp PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "D:/Development/op3d_active/hdf5-1.8.13/msvc/bin/RelWithDebInfo/hdf5_hl_cpp.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELWITHDEBINFO "hdf5_hl;hdf5"
  IMPORTED_LOCATION_RELWITHDEBINFO "D:/Development/op3d_active/hdf5-1.8.13/msvc/bin/RelWithDebInfo/hdf5_hl_cpp.dll"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
